### ISSUE TITLE
Setup Prometheus for Meson

### ISSUE THREAD

**Issue by Mikerah** [hashcloak/Meson#18]
Prometheus is used for monitoring and tracking servers. This will be a good tool to use for helping people manage their providers, mixes, etc.

**Comment by sebohe** [comment]
Prometheus is setup in one of our cloud servers. It is currently only used to obtain data from [docker swarm](https://docs.docker.com/config/thirdparty/prometheus/) since the mixnet nodes don't have prometheus enabled exporters: https://prometheus.io/docs/instrumenting/writing_exporters/

What I think we can do moving forward is to have a better scope for this issue is:

- Create a separate issue to add the prometheus exporters to the mixnet nodes with a clear idea of which metrics we want to measure.
- Add alerts to the prometheus config [file](https://github.com/sebohe/meson-scripts/blob/master/prometheus.sh#L2) or add grafana since it has a login page (prometheus doesn't have user management or a login page). I think grafana offers more alerting options, user management and persistence of the graphs.
