### ISSUE TITLE
Modularize docker components

### ISSUE THREAD

**Issue by Mikerah** [hashcloak/Meson#47]
Right now, we have a monolithic docker compose network that creates one mixnet. We need a more modularize approach where anyone can spin up any kind of node.

**Comment by sebohe** [comment]
One of the issues that is helping to get this done is https://github.com/hashcloak/Meson/issues/27

When the entry scripts are done this gives us more control over the config files.

I think the requirements to close this issue is to create a Meson testnetwork that doesn't require the docker-compose. In other words running the docker containers on different servers.

**Comment by Mikerah** [comment]
An issue we encountered is that each docker container had difficulties talking to each other when deployed through a test cloud instance. This issue has been documented in [katzenpost/server](https://github.com/katzenpost/server/issues/131) and a potential fix is by configuring the `AltAddresses` map ([here](https://github.com/katzenpost/server/blob/master/config/config.go#L93)) in the servers (provider and mixes) config file.

**Comment by sebohe** [comment]
Using the `AltAddresses` made the modularized (modularized means seperated docker containers for each mixnet node) docker mixnet network to work. 

The following is a working provider config. Take node of the following values:
- `Server.Addresses` -> Notice the `0.0.0.0` Address. This for the node to receive connections from any address. This allows the connection to go through the docker network to the application inside.
- `Server.OnlyAdvertiseAltAddresses` -> Is a public ipv4 address.
- `Server.AltAddresses.tcp4` <- Possible values are `tcp`, `tcp4` and `tcp6`. The value `tcp` did not work due to this: https://github.com/katzenpost/authority/blob/master/internal/s11n/descriptor.go#L166
-  `EnableUserRegistrationHTTP`
- `UserRegistrationHTTPAddresses` -> Notice the `0.0.0.0` Address.
- `AdvertiseUserRegistrationHTTPAddresses` ->  Is a public ipv4 address.
```
[Server]
  Identifier = "provider-0"
  Addresses = ["0.0.0.0:30001"]
  OnlyAdvertiseAltAddresses = true
  DataDir = "/conf"
  IsProvider = true
  [Server.AltAddresses]
    tcp4 = ["163.172.177.34:30001"]

[Logging]
  Disable = false
  File = "katzenpost.log"
  Level = "DEBUG"

[Provider]
  EnableUserRegistrationHTTP = true
  UserRegistrationHTTPAddresses = ["0.0.0.0:40001"]
  AdvertiseUserRegistrationHTTPAddresses = ["http://163.172.177.34:40001"]

  [[Provider.Kaetzchen]]
    Capability = "loop"
    Endpoint = "+loop"
    Disable = false

  [Provider.UserDB]
    Backend = "bolt"
    [Provider.UserDB.Bolt]
      UserDB = "/conf/users.db"
  [Provider.SpoolDB]
    Backend = "bolt"
    [Provider.SpoolDB.Bolt]
      SpoolDB = "/conf/spool.db"

  [[Provider.CBORPluginKaetzchen]]
    Capability = "echo"
    Endpoint = "+echo"
    Command = "/go/bin/echo_server"
    MaxConcurrency = 1
    Disable = false
    [Provider.CBORPluginKaetzchen.Config]
      log_dir = "/conf"
      log_level = "DEBUG"

  [[Provider.CBORPluginKaetzchen]]
    Capability = "panda"
    Endpoint = "+panda"
    Command = "/go/bin/panda_server"
    MaxConcurrency = 1
    Disable = false
    [Provider.CBORPluginKaetzchen.Config]
      fileStore = "/conf/panda.storage"
      log_dir = "/conf"
      log_level = "DEBUG"

  [[Provider.CBORPluginKaetzchen]]
    Capability = "spool"
    Endpoint = "+spool"
    Command = "/go/bin/memspool"
    MaxConcurrency = 1
    Disable = false
    [Provider.CBORPluginKaetzchen.Config]
      data_store = "/conf/memspool.storage"
      log_dir = "/conf"

  [[Provider.CBORPluginKaetzchen]]
    Capability = "gor"
    Endpoint = "+gor"
    Command = "/go/bin/Meson"
    MaxConcurrency = 1
    Disable = false
    [Provider.CBORPluginKaetzchen.Config]
      f = "/conf/currency.toml"
      log_dir = "/conf"
      log_level = "DEBUG"

[PKI]
  [PKI.Nonvoting]
    Address = "163.172.177.34:30000"
    PublicKey = "PQW/MARlKihqLhzMYyoXiqaO+Vyq53uRuLjU6kQ3jWs="

[Management]
  Enable = true
  Path = "/conf/management_sock"

[Debug]
  DisableRateLimit = true

```
